const getProjectData = () => {
  return [
    {
      id: 1,
      language: 'HTML, CSS, JS',
      projectTitle: 'Perfume E-Commerce Website',
      projectDef: 'No integrated payment yet and undeployed. User can view and order through catalogue and the data will be sent to admin side and DB. ',
      projectUrl: 'https://github.com/emelynhadasa/perfume_ecommerce_website',
    },
    {
      id: 2,
      language: 'PHP, MySQL, HTML CSS JS',
      projectTitle: 'Inventory Management System',
      projectDef: 'Undeployed. User can do CRUD of Inventory. ',
      projectUrl: 'https://github.com/emelynhadasa/inventory_system',
    },
    {
      id: 3,
      language: 'Java GUI',
      projectTitle: 'Project Management System',
      projectDef: 'Not interactive and has simplest input. Only to prove the ability of Java GUI to create certain UI.',
      projectUrl: 'https://github.com/emelynhadasa/project-management-system',
    },
    {
      id: 4,
      language: 'HTML, CSS, JS',
      projectTitle: 'Indonesia Website',
      projectDef: 'Web with bunches of multi-medias. Enable user to view videos, hear explanations, facts, also play puzzles. ',
      projectUrl: 'https://github.com/emelynhadasa/indonesia-website',
    },
    {
      id: 5,
      language: 'Java (Android Studio)',
      projectTitle: 'Campus Event Application',
      projectDef: 'Enable students to view and input event and its details. CRUD completed. Has a Guide-Book. ',
      projectUrl: 'https://github.com/emelynhadasa/event-mobile-app',
    },
    {
      id: 6,
      language: 'HTML CSS JS, API',
      projectTitle: 'Bookshelf App',
      projectDef: 'Enable user to enter new book list, search the book, and tick the book as finished. ',
      projectUrl: 'https://github.com/emelynhadasa/bookshelf_apps',
    },
    {
      id: 7,
      language: 'Machine-Learning',
      projectTitle: 'Rock-Paper-Scissor Model',
      projectDef: 'Using Google Collab, succeed 98% similarity. ',
      projectUrl: 'https://github.com/emelynhadasa/rock-paper-scissor',
    },
    {
      id: 8,
      language: 'HTML, CSS, JS',
      projectTitle: 'To-Do-List App',
      projectDef: 'CRUD App to note all to-dos. ',
      projectUrl: 'https://github.com/emelynhadasa/todo_apps',
    },
    {
      id: 9,
      language: 'HTML, CSS, JS (Advanced)',
      projectTitle: 'Restaurant Catalogue',
      projectDef: 'All FE optimized. Enable user to review each restaurant, add them into wish-list, and load image without lag.',
      projectUrl: 'https://github.com/emelynhadasa/Restaurant-App-FEExpert',
    },
    {
      id: 10,
      language: 'HTML CSS JS, React',
      projectTitle: 'Notes App',
      projectDef: 'Enable user to do CRUD Notes. Can archive notes.',
      projectUrl: 'https://github.com/emelynhadasa/notes-app-react',
    },
    {
      id: 11,
      language: 'HTML, CSS, JS',
      projectTitle: 'Book-Reviews Website',
      projectDef: 'The simplest form of a website. Linked each book to shop links.',
      projectUrl: 'https://github.com/emelynhadasa/book-review-website',
    },
    {
      id: 12,
      language: 'HTML CSS JS, Open-source API',
      projectTitle: 'Dictionary & PoS App',
      projectDef: 'Enable user to input keyword and app will give output of the word’s definition and Part-of-Speech. Also audio of word’s pronunciation.',
      projectUrl: 'https://github.com/emelynhadasa/word-look-up',
    },
    {
      id: 13,
      language: 'HTML CSS JS',
      projectTitle: 'Purchase-Order Management System',
      projectDef: 'A Purchase-Order Management System (POMS) that is created by my campus team. Including features such as: Supplier, Item, PO, Bills, and Expenditure. ',
      projectUrl: 'https://github.com/emelynhadasa/purchasing-system',
    },
    {
      id: 14,
      language: 'HTML CSS ReactJS, Leaflet',
      projectTitle: 'Mini Restaurants Mapsite',
      projectDef: 'A website utilizing Leaflet, a JavaScript library, to map the region of Kos behind PLN for President University students to explore hidden wartegs.',
      projectUrl: 'https://github.com/emelynhadasa/warteg-mapsite',
    },
    {
      id: 15,
      language: 'React and Laravel',
      projectTitle: 'Mediqueue Clinic App',
      projectDef: 'A website that streamline the processes within a clinic, in aim to improve conventional clinic queueing process.',
      projectUrl: 'https://github.com/orgs/MediQueue-Dicoding-Bootcamp-Capstone/repositories',
    },
    {
      id: 16,
      language: 'MERN Stack',
      projectTitle: 'MERN Integration Challenge',
      projectDef: 'As a completion of MERN certification challenge.',
      projectUrl: 'https://github.com/emelynhadasa/express-cikarang',
    },
    {
      id: 17,
      language: 'React and JavaSpring',
      projectTitle: 'FreshFold Laundry Management System',
      projectDef: 'A laundry management system that streamline the process of laundry and digitalize conventional bills.',
      projectUrl: 'https://github.com/emelynhadasa/lms-fe',
    },
  ]
}

export { getProjectData }
